# Generated by Django 6.1.2 on 2026-10-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
