# Generated by Django 6.1.2 on 2026-10-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_pedido_cantidad_pedido_nombre_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='activo',
            new_name='entregado',
        ),
    ]
